---
- name: Autoware (install pip)
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  become: yes

- name: Autoware (update rosdep)
  command: rosdep update
  become: yes
  
- name: Autoware (remove Multiple packages )
  command: "rm -rf {{ WORKSPACE_ROOT }}/src/description/sensor/sensor_component_description/velodyne_description"
  become: yes
  
- name: Autoware (clone tier_4_msgs )
  command: "mkdir {{ WORKSPACE_ROOT }}/src/tier4_autoware_msgs"
  become: yes
  
- name: Autoware (clone tier_4_msgs )
  command: "git clone git@github.com:tier4/tier4_autoware_msgs.git {{ WORKSPACE_ROOT }}/src/tier4_autoware_msgs"
  become: yes

- name: Autoware (vcs import tier_4_msgs_dpends)
  command: "vcs import {{ WORKSPACE_ROOT }}/src/tier4_autoware_msgs < {{ WORKSPACE_ROOT }}/src/tier4_autoware_msgs/build_depends.repos"
  become: yes

- name: Autoware (rosdep install dependencies)
  command: "rosdep install -y --from-paths {{ WORKSPACE_ROOT }}/src --ignore-src --rosdistro {{ rosdistro }}"
  become: yes

- name: Autoware (install gdown to download some files for neural network)
  pip:
    name:
      - gdown
    executable: pip3
  become: yes

- name: Autoware (install geographiclib-tools)
  apt:
    name: geographiclib-tools
    state: latest
    update_cache: yes
  become: yes

- name: Autoware (install egm2008-1)
  shell: geographiclib-get-geoids egm2008-1
  become: yes
