

---
- hosts: localhost
  connection: local
  become: no
  roles:
   # - { role: cuda, when: yn_gpu == 'y', tags: ["cuda"] }
   # - { role: tensorrt, when: yn_gpu == 'y', tags: ["tensorrt"] }
    - { role: ros2, rosdistro: galactic, tags: ["ros2"] }
   # - { role: autoware, rosdistro: galactic, tags: ["autoware"] }
   # - { role: pacmod, rosdistro: galactic, tags: ["pacmod"] }
   # - { role: libtorch, tags: ["libtorch"] }
